version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: keycloak-biblioteca
    command: ["start-dev", "--import-realm"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./biblioteca-realm.json:/opt/keycloak/data/import/biblioteca-realm.json
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
